2025-08-26 22:56:46,564 INFO    MainThread:35285 [wandb_setup.py:_flush():80] Current SDK version is 0.21.1
2025-08-26 22:56:46,564 INFO    MainThread:35285 [wandb_setup.py:_flush():80] Configure stats pid to 35285
2025-08-26 22:56:46,564 INFO    MainThread:35285 [wandb_setup.py:_flush():80] Loading settings from /home/mahin-sanklecha/.config/wandb/settings
2025-08-26 22:56:46,564 INFO    MainThread:35285 [wandb_setup.py:_flush():80] Loading settings from /home/mahin-sanklecha/alpha-RACER/car_ros2/car_ros2/wandb/settings
2025-08-26 22:56:46,564 INFO    MainThread:35285 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-08-26 22:56:46,564 INFO    MainThread:35285 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /home/mahin-sanklecha/alpha-RACER/car_ros2/car_ros2/wandb/run-20250826_225646-gnyx0gff/logs/debug.log
2025-08-26 22:56:46,564 INFO    MainThread:35285 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /home/mahin-sanklecha/alpha-RACER/car_ros2/car_ros2/wandb/run-20250826_225646-gnyx0gff/logs/debug-internal.log
2025-08-26 22:56:46,564 INFO    MainThread:35285 [wandb_init.py:init():830] calling init triggers
2025-08-26 22:56:46,564 INFO    MainThread:35285 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'exp_name': 'data9_multi', 'start_ep': 226, 'end_ep': 242, 'use_wandb': True, 'wandb_project': 'alpha-racer-data', 'wandb_entity': None, 'checkpoint_dir': 'data', 'mid_ckpt_steps': 0, 'seed': -1, 'wandb_max_retries': 3, 'wandb_retry_backoff': 2.0, 'controller': 'mpc', 'exp_name_effective': 'data9_multi_mpc', 'episode_start': 228, 'episode_end': 242, 'seed_base': 1756229197, '_wandb': {}}
2025-08-26 22:56:46,565 INFO    MainThread:35285 [wandb_init.py:init():871] starting backend
2025-08-26 22:56:46,775 INFO    MainThread:35285 [wandb_init.py:init():874] sending inform_init request
2025-08-26 22:56:46,781 INFO    MainThread:35285 [wandb_init.py:init():882] backend started and connected
2025-08-26 22:56:46,784 INFO    MainThread:35285 [wandb_init.py:init():953] updated telemetry
2025-08-26 22:56:46,792 INFO    MainThread:35285 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-08-26 22:56:48,216 INFO    MainThread:35285 [wandb_init.py:init():1029] starting run threads in backend
2025-08-26 22:56:48,692 INFO    MainThread:35285 [wandb_run.py:_console_start():2494] atexit reg
2025-08-26 22:56:48,692 INFO    MainThread:35285 [wandb_run.py:_redirect():2342] redirect: wrap_raw
2025-08-26 22:56:48,693 INFO    MainThread:35285 [wandb_run.py:_redirect():2411] Wrapping output streams.
2025-08-26 22:56:48,693 INFO    MainThread:35285 [wandb_run.py:_redirect():2434] Redirects installed.
2025-08-26 22:56:48,696 INFO    MainThread:35285 [wandb_init.py:init():1075] run started, returning control to user process
2025-08-27 09:32:06,831 INFO    MsgRouterThr:35285 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 2 handles.
2025-08-27 09:32:07,198 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,200 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,201 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,202 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,203 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,204 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,205 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,205 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,206 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,207 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,208 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,209 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,209 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,210 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,211 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,212 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,212 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,213 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,214 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,215 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,216 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,216 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,218 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,218 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,219 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,220 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,221 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,222 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,222 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,223 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,224 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,224 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-27 09:32:07,225 ERROR   MainThread:35285 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
