2025-08-31 14:10:18,210 INFO    MainThread:123714 [wandb_setup.py:_flush():80] Current SDK version is 0.21.1
2025-08-31 14:10:18,210 INFO    MainThread:123714 [wandb_setup.py:_flush():80] Configure stats pid to 123714
2025-08-31 14:10:18,210 INFO    MainThread:123714 [wandb_setup.py:_flush():80] Loading settings from /home/mahin-sanklecha/.config/wandb/settings
2025-08-31 14:10:18,210 INFO    MainThread:123714 [wandb_setup.py:_flush():80] Loading settings from /home/mahin-sanklecha/alpha-RACER/car_ros2/car_ros2/wandb/settings
2025-08-31 14:10:18,210 INFO    MainThread:123714 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-08-31 14:10:18,210 INFO    MainThread:123714 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /home/mahin-sanklecha/alpha-RACER/car_ros2/car_ros2/wandb/run-20250831_141018-uluz52bp/logs/debug.log
2025-08-31 14:10:18,210 INFO    MainThread:123714 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /home/mahin-sanklecha/alpha-RACER/car_ros2/car_ros2/wandb/run-20250831_141018-uluz52bp/logs/debug-internal.log
2025-08-31 14:10:18,210 INFO    MainThread:123714 [wandb_init.py:init():830] calling init triggers
2025-08-31 14:10:18,210 INFO    MainThread:123714 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-08-31 14:10:18,210 INFO    MainThread:123714 [wandb_init.py:init():871] starting backend
2025-08-31 14:10:18,416 INFO    MainThread:123714 [wandb_init.py:init():874] sending inform_init request
2025-08-31 14:10:18,420 INFO    MainThread:123714 [wandb_init.py:init():882] backend started and connected
2025-08-31 14:10:18,420 INFO    MainThread:123714 [wandb_init.py:init():953] updated telemetry
2025-08-31 14:10:18,425 INFO    MainThread:123714 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-08-31 14:10:19,377 INFO    MainThread:123714 [wandb_init.py:init():1029] starting run threads in backend
2025-08-31 14:10:19,556 INFO    MainThread:123714 [wandb_run.py:_console_start():2494] atexit reg
2025-08-31 14:10:19,556 INFO    MainThread:123714 [wandb_run.py:_redirect():2342] redirect: wrap_raw
2025-08-31 14:10:19,556 INFO    MainThread:123714 [wandb_run.py:_redirect():2411] Wrapping output streams.
2025-08-31 14:10:19,556 INFO    MainThread:123714 [wandb_run.py:_redirect():2434] Redirects installed.
2025-08-31 14:10:19,558 INFO    MainThread:123714 [wandb_init.py:init():1075] run started, returning control to user process
2025-08-31 15:42:31,457 INFO    MsgRouterThr:123714 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-08-31 15:42:31,839 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,841 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,842 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,842 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,842 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,842 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,843 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,843 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,843 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,843 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,844 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,844 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,844 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,844 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,845 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,845 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,845 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,846 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,846 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,847 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,847 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,847 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,848 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,848 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,849 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,849 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,849 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,850 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,850 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,870 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,870 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,871 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,871 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,871 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,872 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,872 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,873 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,873 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,873 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,874 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,874 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,874 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,875 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,875 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,876 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,876 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,877 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,878 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,879 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,880 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,881 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,882 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,882 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,882 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,883 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,883 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,883 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,884 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,884 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,884 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,884 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-31 15:42:31,885 ERROR   MainThread:123714 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/mahin-sanklecha/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
